export const PRICING_CONSTANTS = {
  YEARLY_ESSENTIAL_PLAN_ID: process.env.NEXT_PUBLIC_YEARLY_ESSENTIAL_PLAN_ID!,
  YEARLY_PRO_PLAN_ID: process.env.NEXT_PUBLIC_YEARLY_PRO_PLAN_ID!,
  YEARLY_ULTIMATE_PLAN_ID: process.env.NEXT_PUBLIC_YEARLY_ULTIMATE_PLAN_ID!,
  MONTHLY_ESSENTIAL_PLAN_ID: process.env.NEXT_PUBLIC_MONTHLY_ESSENTIAL_PLAN_ID!,
  MONTHLY_PRO_PLAN_ID: process.env.NEXT_PUBLIC_MONTHLY_PRO_PLAN_ID!,
  MONTHLY_ULTIMATE_PLAN_ID: process.env.NEXT_PUBLIC_MONTHLY_ULTIMATE_PLAN_ID!,
  TOKEN_PACKAGE_300K_ID: process.env.NEXT_PUBLIC_TOKEN_PACKAGE_300K_ID!,
  TOKEN_PACKAGE_1M_ID: process.env.NEXT_PUBLIC_TOKEN_PACKAGE_1M_ID!,
  TOKEN_PACKAGE_2M_ID: process.env.NEXT_PUBLIC_TOKEN_PACKAGE_2M_ID!
}

export const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL!
export const AUTH_SECRET = process.env.NEXTAUTH_SECRET!
export const OPEN_ROUTER_API_KEY = process.env.NEXT_PUBLIC_OPENROUTER_API_KEY!
export const GOOGLE_ID = process.env.GOOGLE_ID!
export const GOOGLE_SECRET = process.env.GOOGLE_SECRET!
export const RANDOM_ID_CHARACTERS = process.env.NEXT_PUBLIC_RANDOM_ID_CHARACTERS!
